In [4]:
print(7.7%3)
print(7%3) #remainder
print(7.7/3)
print(int("7.7"))


1.7000000000000002
1
2.566666666666667


ValueError: invalid literal for int() with base 10: '7.7'

In [1]:
d = {1:(3,4) ,2: (5,6), 3:(7,8) } 
print(d[1]+d[2])

d = {1:[3,4] ,2: [5,6], 3:(7,8) } 
print(d[1]+d[2])

(3, 4, 5, 6)
[3, 4, 5, 6]


In [9]:
def square (n):
    n*=n

n=3
print(square(n))
print(n)

#update didnt happen because integers are immutable. If we want to update the value of n, we need to return the value from the function and assign it to n.
#inside the function a local copy of n is created and updated, but the original n remains unchanged.

#such updates will happen if we pass a mutable object like a list or a dictionary to the function.
#example:
def update_list(lst):
    lst.append(4)   

numbers = [1, 2, 3]
print(numbers)  # Output: [1, 2, 3]
update_list(numbers)
print(numbers)  # Output: [1, 2, 3, 4] -> It actually updated!

None
3
[1, 2, 3]
[1, 2, 3, 4]


In [ ]:
num=3
div=3//5 #floor division quotient

try:
    a=num/div
except ValueError :
    print ("ValueError ")
except ZeroDivisionError:
    print ("ZeroDivisionError" )
finally:
    print ("Okey") #finally statement always executes, whether an exception is raised or not.

ZeroDivisionError
Okey


In [14]:
a=[1,1,1]
b=[2,2,2]
c=a+b
c

[1, 1, 1, 2, 2, 2]

In [ ]:
import numpy as np

a=np.ones((3,1))
b=np.ones( (1,4)) 
c=a+b
print (c) 

#In Python, standard lists use the + operator to concatenate (glue them together). However, NumPy arrays use the + operator for element-wise addition.When you try to add two NumPy arrays with different shapes—like a columns vector and a row vector—NumPy uses a powerful feature called broadcasting. Instead of throwing an error or concatenating, NumPy automatically stretches the arrays behind the scenes so their shapes match, and then adds them element-by-element.

#Two dimensions are compatible for NumPy operations if they meet at least one of these two conditions, checking from right to left (starting from the last dimension):
# They are exactly equal
# One of them is exactly 1

# If neither condition is met, NumPy will throw a ValueError: operands could not be broadcast together.

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [28]:
import numpy as np
a=np.eye(3,5).T #dimension of this is (5,3)
b=np.eye (3,5).reshape((5,3)) #dimension of this is (5,3)
print(np.sum(a*b)) 

# print(a)
# print(b)

#for reshaping, you read elements row by row from the original matrix and place them row by row into the new matrix when doing this by hand.4

#In standard mathematics and linear algebra, you cannot multiply two (5x3))matrices together. 
# However, in NumPy, the * operator does not perform traditional matrix multiplication. Instead, it performs element-wise multiplication.Because a and b have the exact same shape, NumPy simply pairs up the elements at identical positions and multiplies them together
#np.sum(a*b) then adds up all those products to give you a single scalar value.

# if a and b had different shapes, we would have to use broadcasting rules to determine if they can be combined element-wise.
#  If they are compatible, NumPy would stretch one or both arrays as needed to make their shapes match before performing the multiplication. If they are not compatible, NumPy would raise a ValueError.

#brodcasting is outer product
a1=np.array([10,20,30]).reshape((3,1)) #dimension of this is (3,1)
b1=np.array([1,2])
print(a1+b1) #dimension of this is (3,2)
print(a1*b1)



1.0
[[11 12]
 [21 22]
 [31 32]]
[[10 20]
 [20 40]
 [30 60]]
